name: Godot Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Godot Headless Export Test
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.godotengine.org/?version=4.8&flavor=dev4&slug=linux.x86_64.zip&platform=linux.64
          godot_export_templates_download_url: https://downloads.godotengine.org/?version=4.8&flavor=dev4&slug=export_templates.tpz&platform=templates
          relative_project_path: ./
          archive_output: false
